version: "1"
services:
  database:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    networks:
      - price_tracker
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 2s
      retries: 10
  # console:
  #   build: ./console
  #   image: dotnet-console:1
  #   container_name: dotnet-console
  #   restart: always
  #   env_file:
  #     - .env.dev
  #   networks:
  #     - price_tracker
  #   depends_on:
  #     database: 
  #       condition: service_healthy
  # assessment:
  #   build: ./assessment
  #   image: assessment:1
  #   container_name: assessment
  #   restart: always
  #   ports:
  #     - 5283:5283
  #   env_file:
  #     - .env.dev
  #   networks:
  #     - price_tracker
  #   depends_on:
  #     database:
  #       condition: service_healthy

networks:
  price_tracker: