version: "1"
services:
  database:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    networks:
      - etherscan

networks:
  etherscan: